/* tslint:disable */
/* eslint-disable */
/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FunctionInvocationInvokeFunction200Response } from '../models';
// @ts-ignore
import { FunctionInvocationInvokeFunction202Response } from '../models';
// @ts-ignore
import { FunctionInvocationInvokeFunction302Response } from '../models';
// @ts-ignore
import { FunctionInvocationInvokeFunction402Response } from '../models';
// @ts-ignore
import { FunctionInvocationInvokeFunction403Response } from '../models';
// @ts-ignore
import { FunctionInvocationInvokeFunctionResponseInner } from '../models';
// @ts-ignore
import { FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response } from '../models';
// @ts-ignore
import { FunctionInvocationPollForResultUsingFunctionInvocationRequest302Response } from '../models';
// @ts-ignore
import { FunctionInvocationPollForResultUsingFunctionInvocationRequest402Response } from '../models';
// @ts-ignore
import { FunctionInvocationPollForResultUsingFunctionInvocationRequest403Response } from '../models';
// @ts-ignore
import { FunctionInvocationPollForResultUsingFunctionInvocationRequestResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * FunctionInvocationApi - axios parameter creator
 * @export
 */
export const FunctionInvocationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {string} functionId 
         * @param {object} body 
         * @param {Array<string>} [nvcfInputAssetReferences] 
         * @param {number} [nvcfPollSeconds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeFunction: async (functionId: string, body: object, nvcfInputAssetReferences?: Array<string>, nvcfPollSeconds?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'functionId' is not null or undefined
            assertParamExists('invokeFunction', 'functionId', functionId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('invokeFunction', 'body', body)
            const localVarPath = `/v2/nvcf/pexec/functions/{functionId}`
                .replace(`{${"functionId"}}`, encodeURIComponent(String(functionId !== undefined ? functionId : `-functionId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (nvcfInputAssetReferences) {
                let mapped = nvcfInputAssetReferences.map(value => (<any>"Array<string>" !== "Array<string>") ? JSON.stringify(value) : (value || ""));
                localVarHeaderParameter['NVCF-INPUT-ASSET-REFERENCES'] = mapped.join(COLLECTION_FORMATS["csv"]);
            }

            if (nvcfPollSeconds != null) {
                localVarHeaderParameter['NVCF-POLL-SECONDS'] = typeof nvcfPollSeconds === 'string'
                    ? nvcfPollSeconds
                    : JSON.stringify(nvcfPollSeconds);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: body,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/nvcf/pexec/functions/{functionId}',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {string} functionId 
         * @param {string} versionId 
         * @param {object} body 
         * @param {Array<string>} [nvcfInputAssetReferences] 
         * @param {number} [nvcfPollSeconds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeFunction_1: async (functionId: string, versionId: string, body: object, nvcfInputAssetReferences?: Array<string>, nvcfPollSeconds?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'functionId' is not null or undefined
            assertParamExists('invokeFunction_1', 'functionId', functionId)
            // verify required parameter 'versionId' is not null or undefined
            assertParamExists('invokeFunction_1', 'versionId', versionId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('invokeFunction_1', 'body', body)
            const localVarPath = `/v2/nvcf/pexec/functions/{functionId}/versions/{versionId}`
                .replace(`{${"functionId"}}`, encodeURIComponent(String(functionId !== undefined ? functionId : `-functionId-`)))
                .replace(`{${"versionId"}}`, encodeURIComponent(String(versionId !== undefined ? versionId : `-versionId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (nvcfInputAssetReferences) {
                let mapped = nvcfInputAssetReferences.map(value => (<any>"Array<string>" !== "Array<string>") ? JSON.stringify(value) : (value || ""));
                localVarHeaderParameter['NVCF-INPUT-ASSET-REFERENCES'] = mapped.join(COLLECTION_FORMATS["csv"]);
            }

            if (nvcfPollSeconds != null) {
                localVarHeaderParameter['NVCF-POLL-SECONDS'] = typeof nvcfPollSeconds === 'string'
                    ? nvcfPollSeconds
                    : JSON.stringify(nvcfPollSeconds);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: body,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/nvcf/pexec/functions/{functionId}/versions/{versionId}',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the status of an in-progress or pending request using its unique  invocation request ID. If the result is available, it will be included in  the response, marking the request as fulfilled. Conversely, if the result is  not yet available, the request is deemed pending. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with  \'invoke_function\' scope in the HTTP Authorization header. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Poll For Result Using Function Invocation Request
         * @param {string} requestId Function invocation request id
         * @param {number} [nvcfPollSeconds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pollForResultUsingFunctionInvocationRequest: async (requestId: string, nvcfPollSeconds?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('pollForResultUsingFunctionInvocationRequest', 'requestId', requestId)
            const localVarPath = `/v2/nvcf/pexec/status/{requestId}`
                .replace(`{${"requestId"}}`, encodeURIComponent(String(requestId !== undefined ? requestId : `-requestId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (nvcfPollSeconds != null) {
                localVarHeaderParameter['NVCF-POLL-SECONDS'] = typeof nvcfPollSeconds === 'string'
                    ? nvcfPollSeconds
                    : JSON.stringify(nvcfPollSeconds);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/nvcf/pexec/status/{requestId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FunctionInvocationApi - functional programming interface
 * @export
 */
export const FunctionInvocationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FunctionInvocationApiAxiosParamCreator(configuration)
    return {
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {FunctionInvocationApiInvokeFunctionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invokeFunction(requestParameters: FunctionInvocationApiInvokeFunctionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FunctionInvocationInvokeFunction200Response>> {
            const body: object = {
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.invokeFunction(requestParameters.functionId, body, requestParameters.nvcfInputAssetReferences, requestParameters.nvcfPollSeconds, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {FunctionInvocationApiInvokeFunction0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invokeFunction_1(requestParameters: FunctionInvocationApiInvokeFunction0Request, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FunctionInvocationInvokeFunction200Response>> {
            const body: object = {
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.invokeFunction_1(requestParameters.functionId, requestParameters.versionId, body, requestParameters.nvcfInputAssetReferences, requestParameters.nvcfPollSeconds, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves the status of an in-progress or pending request using its unique  invocation request ID. If the result is available, it will be included in  the response, marking the request as fulfilled. Conversely, if the result is  not yet available, the request is deemed pending. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with  \'invoke_function\' scope in the HTTP Authorization header. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Poll For Result Using Function Invocation Request
         * @param {FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pollForResultUsingFunctionInvocationRequest(requestParameters: FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FunctionInvocationPollForResultUsingFunctionInvocationRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pollForResultUsingFunctionInvocationRequest(requestParameters.requestId, requestParameters.nvcfPollSeconds, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FunctionInvocationApi - factory interface
 * @export
 */
export const FunctionInvocationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FunctionInvocationApiFp(configuration)
    return {
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {FunctionInvocationApiInvokeFunctionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeFunction(requestParameters: FunctionInvocationApiInvokeFunctionRequest, options?: AxiosRequestConfig): AxiosPromise<FunctionInvocationInvokeFunction200Response> {
            return localVarFp.invokeFunction(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Call Function
         * @param {FunctionInvocationApiInvokeFunction0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeFunction_1(requestParameters: FunctionInvocationApiInvokeFunction0Request, options?: AxiosRequestConfig): AxiosPromise<FunctionInvocationInvokeFunction200Response> {
            return localVarFp.invokeFunction_1(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the status of an in-progress or pending request using its unique  invocation request ID. If the result is available, it will be included in  the response, marking the request as fulfilled. Conversely, if the result is  not yet available, the request is deemed pending. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with  \'invoke_function\' scope in the HTTP Authorization header. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
         * @summary Poll For Result Using Function Invocation Request
         * @param {FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pollForResultUsingFunctionInvocationRequest(requestParameters: FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest, options?: AxiosRequestConfig): AxiosPromise<FunctionInvocationPollForResultUsingFunctionInvocationRequestResponse> {
            return localVarFp.pollForResultUsingFunctionInvocationRequest(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for invokeFunction operation in FunctionInvocationApi.
 * @export
 * @interface FunctionInvocationApiInvokeFunctionRequest
 */
export type FunctionInvocationApiInvokeFunctionRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof FunctionInvocationApiInvokeFunction
    */
    readonly functionId: string
    
    /**
    * 
    * @type {Array<string>}
    * @memberof FunctionInvocationApiInvokeFunction
    */
    readonly nvcfInputAssetReferences?: Array<string>
    
    /**
    * 
    * @type {number}
    * @memberof FunctionInvocationApiInvokeFunction
    */
    readonly nvcfPollSeconds?: number
    
} & object

/**
 * Request parameters for invokeFunction_1 operation in FunctionInvocationApi.
 * @export
 * @interface FunctionInvocationApiInvokeFunction0Request
 */
export type FunctionInvocationApiInvokeFunction0Request = {
    
    /**
    * 
    * @type {string}
    * @memberof FunctionInvocationApiInvokeFunction0
    */
    readonly functionId: string
    
    /**
    * 
    * @type {string}
    * @memberof FunctionInvocationApiInvokeFunction0
    */
    readonly versionId: string
    
    /**
    * 
    * @type {Array<string>}
    * @memberof FunctionInvocationApiInvokeFunction0
    */
    readonly nvcfInputAssetReferences?: Array<string>
    
    /**
    * 
    * @type {number}
    * @memberof FunctionInvocationApiInvokeFunction0
    */
    readonly nvcfPollSeconds?: number
    
} & object

/**
 * Request parameters for pollForResultUsingFunctionInvocationRequest operation in FunctionInvocationApi.
 * @export
 * @interface FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest
 */
export type FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest = {
    
    /**
    * Function invocation request id
    * @type {string}
    * @memberof FunctionInvocationApiPollForResultUsingFunctionInvocationRequest
    */
    readonly requestId: string
    
    /**
    * 
    * @type {number}
    * @memberof FunctionInvocationApiPollForResultUsingFunctionInvocationRequest
    */
    readonly nvcfPollSeconds?: number
    
}

/**
 * FunctionInvocationApiGenerated - object-oriented interface
 * @export
 * @class FunctionInvocationApiGenerated
 * @extends {BaseAPI}
 */
export class FunctionInvocationApiGenerated extends BaseAPI {
    /**
     * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
     * @summary Call Function
     * @param {FunctionInvocationApiInvokeFunctionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FunctionInvocationApiGenerated
     */
    public invokeFunction(requestParameters: FunctionInvocationApiInvokeFunctionRequest, options?: AxiosRequestConfig) {
        return FunctionInvocationApiFp(this.configuration).invokeFunction(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invokes the specified function that was successfully deployed. If the version  is not specified, any active function versions will handle the request. If  the version is specified in the URI, then the request is exclusively processed  by the designated version of the function. By default, this endpoint will block  for 5 seconds. If the request is not fulfilled before the timeout, it\'s status  is considered in-progress or pending and the response includes HTTP status code  202 with an invocation request ID, indicating that the client should commence  polling for the result using the invocation request ID. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with \'invoke_function\'  scope in the HTTP Authorization header. Additionally, this endpoint has the  capability to provide updates on the progress of the request, contingent  upon the workload\'s provision of such information. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
     * @summary Call Function
     * @param {FunctionInvocationApiInvokeFunction0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FunctionInvocationApiGenerated
     */
    public invokeFunction_1(requestParameters: FunctionInvocationApiInvokeFunction0Request, options?: AxiosRequestConfig) {
        return FunctionInvocationApiFp(this.configuration).invokeFunction_1(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the status of an in-progress or pending request using its unique  invocation request ID. If the result is available, it will be included in  the response, marking the request as fulfilled. Conversely, if the result is  not yet available, the request is deemed pending. Access to this endpoint  mandates inclusion of either a bearer token or an api-key with  \'invoke_function\' scope in the HTTP Authorization header. In-progress responses are returned in order. If no in-progress response is received  during polling you will receive the most recent in-progress response. Only the first  256 unread in-progress messages are kept. 
     * @summary Poll For Result Using Function Invocation Request
     * @param {FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FunctionInvocationApiGenerated
     */
    public pollForResultUsingFunctionInvocationRequest(requestParameters: FunctionInvocationApiPollForResultUsingFunctionInvocationRequestRequest, options?: AxiosRequestConfig) {
        return FunctionInvocationApiFp(this.configuration).pollForResultUsingFunctionInvocationRequest(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
