/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthorizedPartyDto } from './authorized-party-dto';

/**
 * Data Transfer Object(DTO) representing a function with authorized accounts
 * @export
 * @interface AuthorizedPartiesByFunctionDto
 */
export interface AuthorizedPartiesByFunctionDto {
    /**
     * Function id
     * @type {string}
     * @memberof AuthorizedPartiesByFunctionDto
     */
    'id': string;
    /**
     * NVIDIA Cloud Account Id
     * @type {string}
     * @memberof AuthorizedPartiesByFunctionDto
     */
    'ncaId': string;
    /**
     * Function version id
     * @type {string}
     * @memberof AuthorizedPartiesByFunctionDto
     */
    'versionId'?: string;
    /**
     * Authorized parties allowed to invoke the function
     * @type {Array<AuthorizedPartyDto>}
     * @memberof AuthorizedPartiesByFunctionDto
     */
    'authorizedParties'?: Array<AuthorizedPartyDto>;
}

