/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Data Transfer Object(DTO) representing deployment error
 * @export
 * @interface DeploymentHealthDto
 */
export interface DeploymentHealthDto {
    /**
     * SIS Request ID
     * @type {string}
     * @memberof DeploymentHealthDto
     */
    'sisRequestId'?: string;
    /**
     * GPU Type as per SDD
     * @type {string}
     * @memberof DeploymentHealthDto
     */
    'gpu': string;
    /**
     * Backend/CSP where the GPU powered instance will be launched
     * @type {string}
     * @memberof DeploymentHealthDto
     */
    'backend': string;
    /**
     * Instance type
     * @type {string}
     * @memberof DeploymentHealthDto
     */
    'instanceType'?: string;
    /**
     * Deployment error
     * @type {string}
     * @memberof DeploymentHealthDto
     */
    'error': string;
}

