/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ArtifactDto } from './artifact-dto';
import { ContainerEnvironmentEntryDto } from './container-environment-entry-dto';
import { InstanceDto } from './instance-dto';

/**
 * Data Transfer Object(DTO) representing a function
 * @export
 * @interface FunctionDto
 */
export interface FunctionDto {
    /**
     * Unique function id
     * @type {string}
     * @memberof FunctionDto
     */
    'id': string;
    /**
     * NVIDIA Cloud Account Id
     * @type {string}
     * @memberof FunctionDto
     */
    'ncaId': string;
    /**
     * Unique function version id
     * @type {string}
     * @memberof FunctionDto
     */
    'versionId': string;
    /**
     * Function name
     * @type {string}
     * @memberof FunctionDto
     */
    'name': string;
    /**
     * Function status
     * @type {string}
     * @memberof FunctionDto
     */
    'status': FunctionDtoStatusEnum;
    /**
     * Entrypoint for invoking the container to process requests
     * @type {string}
     * @memberof FunctionDto
     */
    'inferenceUrl'?: string;
    /**
     * Indicates whether the function is owned by another account. If the account  that is being used to lookup functions happens to be authorized to invoke/list  this function which is owned by a different account, then this field is set  to true and ncaId will contain the id of the account that owns the function.  Otherwise, this field is not set as it defaults to false. 
     * @type {boolean}
     * @memberof FunctionDto
     */
    'ownedByDifferentAccount'?: boolean;
    /**
     * Optional port number where the inference listener is running - defaults to 8000 for Triton
     * @type {number}
     * @memberof FunctionDto
     */
    'inferencePort'?: number;
    /**
     * Args used to launch the container
     * @type {string}
     * @memberof FunctionDto
     */
    'containerArgs'?: string;
    /**
     * Environment settings used to launch the container
     * @type {Array<ContainerEnvironmentEntryDto>}
     * @memberof FunctionDto
     */
    'containerEnvironment'?: Array<ContainerEnvironmentEntryDto>;
    /**
     * Optional set of models
     * @type {Set<ArtifactDto>}
     * @memberof FunctionDto
     */
    'models'?: Set<ArtifactDto>;
    /**
     * Optional custom container
     * @type {string}
     * @memberof FunctionDto
     */
    'containerImage'?: string;
    /**
     * Invocation request body format
     * @type {string}
     * @memberof FunctionDto
     */
    'apiBodyFormat'?: FunctionDtoApiBodyFormatEnum;
    /**
     * Optional Helm Chart
     * @type {string}
     * @memberof FunctionDto
     */
    'helmChart'?: string;
    /**
     * Helm Chart Service Name specified only when helmChart property is specified 
     * @type {string}
     * @memberof FunctionDto
     */
    'helmChartServiceName'?: string;
    /**
     * Health endpoint for the container or helmChart
     * @type {string}
     * @memberof FunctionDto
     */
    'healthUri': string;
    /**
     * Function creation timestamp
     * @type {string}
     * @memberof FunctionDto
     */
    'createdAt': string;
    /**
     * List of active instances for this function.
     * @type {Array<InstanceDto>}
     * @memberof FunctionDto
     */
    'activeInstances'?: Array<InstanceDto>;
    /**
     * Optional set of resources.
     * @type {Set<ArtifactDto>}
     * @memberof FunctionDto
     */
    'resources'?: Set<ArtifactDto>;
}

type FunctionDtoStatusEnum = 'ACTIVE' | 'DEPLOYING' | 'ERROR' | 'INACTIVE' | 'DELETED'
type FunctionDtoApiBodyFormatEnum = 'PREDICT_V2' | 'CUSTOM'


