/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeploymentHealthDto } from './deployment-health-dto';
import { GpuSpecificationDto } from './gpu-specification-dto';

/**
 * Function deployment response
 * @export
 * @interface FunctionDeploymentDto
 */
export interface FunctionDeploymentDto {
    /**
     * Function id
     * @type {string}
     * @memberof FunctionDeploymentDto
     */
    'functionId': string;
    /**
     * Function version id
     * @type {string}
     * @memberof FunctionDeploymentDto
     */
    'functionVersionId': string;
    /**
     * NVIDIA Cloud Account Id
     * @type {string}
     * @memberof FunctionDeploymentDto
     */
    'ncaId': string;
    /**
     * Function status
     * @type {string}
     * @memberof FunctionDeploymentDto
     */
    'functionStatus': FunctionDeploymentDtoFunctionStatusEnum;
    /**
     * SQS Request Queue URL
     * @type {string}
     * @memberof FunctionDeploymentDto
     */
    'requestQueueUrl': string;
    /**
     * Health info for a deployment specification is included only if there are any  issues/errors. 
     * @type {Array<DeploymentHealthDto>}
     * @memberof FunctionDeploymentDto
     */
    'healthInfo'?: Array<DeploymentHealthDto>;
    /**
     * Function deployment details
     * @type {Array<GpuSpecificationDto>}
     * @memberof FunctionDeploymentDto
     */
    'deploymentSpecifications': Array<GpuSpecificationDto>;
}

type FunctionDeploymentDtoFunctionStatusEnum = 'ACTIVE' | 'DEPLOYING' | 'ERROR' | 'INACTIVE' | 'DELETED'


