/*
Cloud Functions

Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

The version of the OpenAPI document: 2.87.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Data Transfer Object(DTO) representing GPU specification.
 * @export
 * @interface GpuSpecificationDto
 */
export interface GpuSpecificationDto {
    /**
     * GPU name from the cluster
     * @type {string}
     * @memberof GpuSpecificationDto
     */
    'gpu': string;
    /**
     * Backend/CSP where the GPU powered instance will be launched
     * @type {string}
     * @memberof GpuSpecificationDto
     */
    'backend': string;
    /**
     * Maximum number of spot instances for the deployment
     * @type {number}
     * @memberof GpuSpecificationDto
     */
    'maxInstances': number;
    /**
     * Minimum number of spot instances for the deployment
     * @type {number}
     * @memberof GpuSpecificationDto
     */
    'minInstances': number;
    /**
     * Instance type, based on GPU, assigned to a Worker
     * @type {string}
     * @memberof GpuSpecificationDto
     */
    'instanceType'?: string;
    /**
     * List of availability-zones(or clusters) in the cluster group
     * @type {Array<string>}
     * @memberof GpuSpecificationDto
     */
    'availabilityZones'?: Array<string>;
    /**
     * Max request concurrency between 1 (default) and 1024.
     * @type {number}
     * @memberof GpuSpecificationDto
     */
    'maxRequestConcurrency'?: number;
    /**
     * 
     * @type {object}
     * @memberof GpuSpecificationDto
     */
    'configuration'?: object;
}

